FROM nvcr.io/nvidia/tritonserver:24.01-py3

# Install UV
ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

# Install dependencies
RUN apt update && \
    apt install -y libgl1 && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements/requirements-triton.txt .
RUN /root/.cargo/bin/uv pip install --system --no-cache -r requirements-triton.txt