version: '3'
services:
  web:
    container_name: Celebrity-Look-Alike-Web
    build: .
    restart: always
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - kibana
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count:  1
              capabilities: [gpu]
    devices:
      - /dev/video0:/dev/video0
    networks:
      mynet:
        ipv4_address: 10.5.0.3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:   
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      mynet:
        ipv4_address: 10.5.0.4
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      mynet:
        ipv4_address: 10.5.0.5

networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1