name: "pipeline"
backend: "python"
max_batch_size : 0

input [
    {
      name: "input_image"
      data_type: TYPE_UINT8
      dims: [ -1, -1, -1 ]
    }
]

output [
  {
    name: "embedding_output"
    data_type: TYPE_FP32
    dims: [ -1, 512 ] 
  }
]

output [
    {
      name: "coordinates"
      dims: [-1,4]
      data_type: TYPE_INT16
    }
]

output [
  {
    name: "cropped_faces"
    data_type: TYPE_FP32
    dims: [-1, 160, 160, 3 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]
